version: '3.9'  

services:
  django:
    build: .
    container_name: django
    command: sh -c "python app/manage.py migrate &&
      python app/create_superuser.py && python app/manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/app
    ports:
      - 8000:8000

    depends_on:
      - pgdb

  pgdb:
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/ 
volumes:
  pgdbdata: 

























