version: '3.9'  

services:
  django:
    build: .
    container_name: django
    command: sh -c "python manage.py migrate &&
      python create_superuser.py && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/user/src/service_app/
    ports:
      - 8000:8000

    depends_on:
      - database

  database:
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/ 
volumes:
  pgdbdata:
























